name: Análise de Código
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    # types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instala dependências
        run: yarn

      - name: Executa linter
        run: yarn lint

      - name: Executa testes e gera cobertura
        run: yarn test:all
        env:
          URL_USER_SERVICE: ${{secrets.URL_USER_SERVICE}}
          URL_PRNTER_SERVICE: ${{secrets.URL_PRINTER_SERVICE}}
          URL_SCHEDULER_SERVICE: ${{secrets.URL_SCHEDULER_SERVICE}}

      - name: Executa SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          URL_USER_SERVICE: ${{secrets.URL_USER_SERVICE}}
          URL_PRNTER_SERVICE: ${{secrets.URL_PRINTER_SERVICE}}
          URL_SCHEDULER_SERVICE: ${{secrets.URL_SCHEDULER_SERVICE}}

      - name: Envia cobertura para o Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: jest
          name: 2023.2-PrintGo-ApiGateway
          verbose: true
